module	boxMatrixBitMap	(	
					input	logic	clk,
					input	logic	resetN,
					input logic	[10:0] offsetX,// offset from top left  position 
					input logic	[10:0] offsetY,
					input	logic	InsideRectangle, //input that the pixel is within a bracket 
					//input logic random_mat,
					
					//------------------------input collision smiley and box					
					input collision,
					
					//------------------------input to pick random 
					input [2:0] random_matrix_pick,
					

					output	logic	drawingRequest, //output that the pixel should be dispalyed 
					output	logic	[7:0] RGBout,  //rgb value from the bitmap 
					
					//-------------------------------------
					output logic box_hit, 
					output logic wall_hit,
					output logic game_won
					//-------------------------------------
 ) ;
 
 
 
// this is the devider used to acess the right pixel 
localparam  int OBJECT_NUMBER_OF_Y_BITS = 5;  // 2^5 = 32 
localparam  int OBJECT_NUMBER_OF_X_BITS = 5;  // 2^5 = 32 


localparam  int OBJECT_HEIGHT_Y = 1 <<  OBJECT_NUMBER_OF_Y_BITS ;
localparam  int OBJECT_WIDTH_X = 1 <<  OBJECT_NUMBER_OF_X_BITS;

// Size represented as Number of X and Y bits 
localparam logic [7:0] TRANSPARENT_ENCODING = 8'hFF ;// RGB value in the bitmap representing a transparent pixel 
 /*  end generated by the tool */


// the screen is 640*480  or  20 * 15 squares of 32*32  bits ,  we wiil round up to 16*16 and use only the top left 16*15 squares 
// this is the bitmap  of the maze , if there is a specific value  the  whole 32*32 rectange will be drawn on the screen
// there are  16 options of differents kinds of 32*32 squares 
// all numbers here are hard coded to simplify the  understanding 


logic [0:15] [0:15] [3:0]  MazeBitMapMask ;  

logic [0:5] [0:15] [0:15] [3:0] MazeDefaultBitMapMask= // defult table to load on reset 
{

 {{64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000020},
 {64'h0000000000020010},
 {64'h0000000000013012},
 {64'h0000000000111011},
 {64'h0000000003121011},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000}},
 
 {{64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000020},
 {64'h0000000000300013},
 {64'h0000000000102011},
 {64'h0000000002101011},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000}},
 
 {{64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000002},
 {64'h0000000000020031},
 {64'h0000000000010011},
 {64'h0000000000121011},
 {64'h0000000030111211},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000}},
 
 {{64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000020},
 {64'h0000000000000010},
 {64'h0000000002302013},
 {64'h0000000001101011},
 {64'h0000000021101011},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000}},
 
 {{64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000002},
 {64'h0000000002000001},
 {64'h0000000001200021},
 {64'h0000000021103011},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000}},
 
 {{64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000011100002},
 {64'h0000000012100021},
 {64'h0000000311100311},
 {64'h0000000000000000},
 {64'h0000000000000000},
 {64'h0000000000000000}}
 
 
 
 
 };

 

 

 logic [0:2] [0:OBJECT_HEIGHT_Y-1] [0:OBJECT_WIDTH_X-1] [7:0]  object_colors  = {
	{{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hcc,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hcc},
	{8'hcc,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf4,8'hf0,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf0,8'hf4,8'hf4,8'hf0,8'hf0,8'hf0,8'hf4,8'hf4,8'hf4,8'hcc},
	{8'hcc,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hcc},
	{8'hcc,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf0,8'hf0,8'hf4,8'hf0,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hac},
	{8'hcc,8'hf4,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hac},
	{8'hcc,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf0,8'hf0,8'hf4,8'hf0,8'hf0,8'hf4,8'hf4,8'hf0,8'hf0,8'hac},
	{8'hcc,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf0,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hf4,8'hf0,8'hf4,8'hf4,8'hd0,8'hac},
	{8'hcc,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf4,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf4,8'hf0,8'hf4,8'hf4,8'hd0,8'hac},
	{8'hcc,8'hf0,8'hf0,8'hf4,8'hf0,8'hf0,8'hf4,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf4,8'hf0,8'hf4,8'hf0,8'hd0,8'hac},
	{8'hcc,8'hf0,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf4,8'hf4,8'hf4,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf0,8'hf0,8'hf4,8'hf4,8'hf4,8'hf0,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf4,8'hf4,8'hf0,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf0,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf0,8'hf4,8'hf4,8'hf0,8'hcc,8'ha4},
	{8'hcc,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf0,8'hf4,8'hf4,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf4,8'hf4,8'hf4,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf4,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf4,8'hf4,8'hf4,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf4,8'hf4,8'hf0,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf4,8'hf4,8'hf4,8'hf0,8'hf4,8'hf0,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf4,8'hf4,8'hf4,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf4,8'hf4,8'hf4,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf4,8'hf0,8'hf4,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf4,8'hf4,8'hf4,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf4,8'hf0,8'hf4,8'hf4,8'hf4,8'hf0,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf4,8'hf4,8'hf4,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf4,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf0,8'hf4,8'hf4,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf4,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf0,8'hf4,8'hf4,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf4,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hcc,8'hf4,8'hf4,8'hf0,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hf0,8'hf4,8'hf4,8'hf0,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf0,8'hf4,8'hf4,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf4,8'hf0,8'hcc,8'ha4},
	{8'hcc,8'hf4,8'hf4,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hf0,8'hd0,8'ha4},
	{8'hcc,8'hf4,8'hf4,8'hd0,8'hcc,8'hd0,8'hd0,8'hd0,8'hcc,8'hd0,8'hd0,8'hd0,8'hd0,8'hd0,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hcc,8'hd0,8'hd0,8'hd0,8'hd0,8'hd0,8'hd0,8'hd0,8'hd0,8'hd0,8'hd0,8'ha4},
	{8'hcc,8'hf4,8'hcc,8'hd0,8'hd0,8'hd0,8'hd0,8'hd0,8'hcc,8'hd0,8'hd0,8'hcc,8'hd0,8'hd0,8'hd0,8'hd0,8'hd0,8'hd0,8'hd0,8'hd0,8'hd0,8'hd0,8'hcc,8'hd0,8'hd0,8'hcc,8'hcc,8'hd0,8'hd0,8'hd0,8'hd0,8'ha4},
	{8'hcc,8'hf0,8'hd0,8'hcc,8'hd0,8'hd0,8'hd0,8'hd0,8'hcc,8'hd0,8'hcc,8'hd0,8'hd0,8'hd0,8'hcc,8'hcc,8'hcc,8'hd0,8'hcc,8'hcc,8'hcc,8'hd0,8'hd0,8'hd0,8'hd0,8'hcc,8'hcc,8'hd0,8'hd0,8'hd0,8'hd0,8'ha4},
	{8'hcc,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac,8'hac}},

	{{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h20,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'h2e,8'h2e,8'h2e,8'h2e,8'h20,8'h20,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h2e,8'h2e,8'h73,8'h73,8'h73,8'h73,8'h73,8'h73,8'h20,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h20,8'h2e,8'h2e,8'h73,8'h73,8'h73,8'h73,8'h73,8'h73,8'h73,8'h20,8'hff,8'hff,8'hff,8'hff,8'h00,8'hf6,8'h99,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h20,8'h2e,8'h2e,8'h73,8'h73,8'h73,8'h73,8'h73,8'h73,8'h73,8'h73,8'hff,8'hff,8'hff,8'h00,8'hf6,8'hf6,8'hf6,8'hf6,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'h20,8'h20,8'h20,8'h20,8'h20,8'h2e,8'h2e,8'h73,8'h73,8'h73,8'h73,8'h73,8'h73,8'h73,8'h20,8'hf6,8'hf6,8'h00,8'hf6,8'h34,8'h34,8'h34,8'hf6,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'h2e,8'h2e,8'h2e,8'h73,8'h73,8'h73,8'h73,8'h2e,8'h2e,8'h73,8'h73,8'h73,8'h73,8'h73,8'h73,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h34,8'hf6,8'hf6,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'h20,8'h20,8'h73,8'h73,8'h73,8'h73,8'h73,8'h73,8'h73,8'h2e,8'h2e,8'h2e,8'h00,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h00,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h20,8'h73,8'h73,8'h73,8'h73,8'h73,8'h73,8'h73,8'h20,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h00,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'hf6,8'hf6,8'h20,8'h73,8'h73,8'h73,8'h73,8'h00,8'h2c,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h00,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'h00,8'hf6,8'hf6,8'hf6,8'hf6,8'h00,8'h20,8'h20,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h00,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'h00,8'hf6,8'hf6,8'hf6,8'h30,8'h30,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hb6,8'hf6,8'hf6,8'hf6,8'h30,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h98,8'h98,8'h98,8'h98,8'h98,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h30,8'h30,8'h30,8'hf6,8'h00,8'hff,8'hff},
	{8'hff,8'hff,8'h00,8'hf6,8'hf6,8'hf6,8'h74,8'h74,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h98,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'h98,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hff,8'hff},
	{8'hff,8'h00,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h74,8'hf6,8'hf6,8'h98,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'h98,8'hf6,8'h78,8'hf6,8'hf6,8'hf6,8'h74,8'hf6,8'h00,8'hff},
	{8'hff,8'h00,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h74,8'hf6,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'h98,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h74,8'h00,8'hff},
	{8'hff,8'h00,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h98,8'hf9,8'hf9,8'h2c,8'h2c,8'h2c,8'hf9,8'hf9,8'hf9,8'hbc,8'hf9,8'hf9,8'hbc,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h00,8'hff},
	{8'hff,8'h00,8'hf6,8'hf6,8'hfe,8'h00,8'h00,8'hfe,8'hfe,8'hfe,8'hfe,8'h98,8'hf9,8'hf9,8'h2c,8'h2c,8'h2c,8'hf9,8'hf9,8'h2c,8'h2c,8'h2c,8'hf9,8'hf9,8'hf6,8'h00,8'hfe,8'hfe,8'hfe,8'hfe,8'h70,8'hff},
	{8'hff,8'h00,8'hf6,8'hf6,8'hfe,8'hfe,8'hfe,8'hfe,8'hfe,8'hfe,8'hfe,8'h98,8'hf9,8'hf9,8'h2c,8'h2c,8'h2c,8'hf9,8'hf9,8'h2c,8'h2c,8'h2c,8'hf9,8'hf9,8'h00,8'h00,8'hfe,8'hfe,8'hfe,8'hfe,8'h00,8'hff},
	{8'hff,8'h00,8'hf6,8'hf6,8'h74,8'hfe,8'hfe,8'hfe,8'hfe,8'hfe,8'h74,8'h98,8'hf9,8'hf9,8'hf9,8'h2c,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'h98,8'hfe,8'hfe,8'hfe,8'hfe,8'hfe,8'hfe,8'h00,8'hff},
	{8'hff,8'h00,8'hf6,8'hf6,8'hf6,8'hfe,8'hfe,8'hfe,8'hfe,8'h74,8'hf6,8'hf6,8'h98,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'h98,8'hfe,8'hfe,8'hfe,8'hfe,8'hfe,8'h74,8'h00,8'hff},
	{8'hff,8'h00,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h74,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h98,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'hf9,8'h98,8'h9c,8'hf6,8'hf6,8'h74,8'hde,8'h74,8'hf6,8'hf6,8'h24,8'hff},
	{8'hff,8'hff,8'h00,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h74,8'h74,8'hf6,8'h78,8'h98,8'h98,8'h98,8'h98,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h00,8'hff,8'hff},
	{8'hff,8'hff,8'h00,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h74,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h00,8'h24,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'h00,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h74,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h00,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'h00,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h00,8'h00,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'h00,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h00,8'h00,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'h00,8'h30,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'hf6,8'h00,8'h00,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h91,8'h00,8'h00,8'h00,8'h00,8'h00,8'hf6,8'hf6,8'hf6,8'h00,8'h00,8'h00,8'h00,8'h00,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'h00,8'h00,8'h00,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff}},
	
	

	{{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hda,8'hd6,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hb5,8'hfe,8'hda,8'hda,8'hb6,8'hb6,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hb6,8'hda,8'hb1,8'hb5,8'hb5,8'hd6,8'hda,8'hda,8'hb6,8'hb6,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hda,8'hb6,8'hda,8'hb6,8'hb6,8'hb5,8'hb6,8'hda,8'hda,8'hd6,8'hb6,8'h8d,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hb6,8'hda,8'hda,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hda,8'hb6,8'hb1,8'h8d,8'h91,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hb6,8'hb6,8'hda,8'hda,8'hb5,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hb1,8'h91,8'h91,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hb6,8'hda,8'hda,8'hd6,8'hb6,8'hda,8'hda,8'hb6,8'hb6,8'hb6,8'hb6,8'hb5,8'h91,8'hb5,8'hb1,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hd6,8'hda,8'hda,8'hb6,8'hb5,8'hb6,8'hda,8'hda,8'hb6,8'hb5,8'hb6,8'hb5,8'hb5,8'h91,8'hb5,8'hb5,8'hb5,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hd6,8'hda,8'hd6,8'hb5,8'hb6,8'hda,8'hda,8'hda,8'hb6,8'hb6,8'hb5,8'hb5,8'hb5,8'hb5,8'hb6,8'hb6,8'hb5,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hd6,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hda,8'hda,8'hda,8'hb6,8'hb6,8'hb6,8'hb6,8'hb5,8'hb6,8'hb6,8'hb6,8'hb6,8'h8d,8'h91,8'hff,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hff,8'hda,8'hd6,8'hb1,8'hb6,8'hd6,8'hb5,8'hb6,8'hda,8'hda,8'hda,8'hb6,8'hb1,8'hb5,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hb5,8'hb5,8'hb6,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hda,8'hda,8'hda,8'hb6,8'hb6,8'hb6,8'hb5,8'hb6,8'hda,8'hda,8'hda,8'hb5,8'hb1,8'hb5,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hb5,8'hb1,8'h94,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hff,8'hda,8'hda,8'hb6,8'hb6,8'hb1,8'hb6,8'hb5,8'hb6,8'hb6,8'hb6,8'hb6,8'hb5,8'hb5,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hb5,8'h64,8'h94,8'hff,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hb5,8'hda,8'hd6,8'hb6,8'hb6,8'hb5,8'hb6,8'hb5,8'hb5,8'hb5,8'hb5,8'hb5,8'hb5,8'hb5,8'hb6,8'hb5,8'hb1,8'hb1,8'hb5,8'hb5,8'hb6,8'hb5,8'hb5,8'h90,8'hd9,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hff,8'hb5,8'hb6,8'hb6,8'hb5,8'hb5,8'h91,8'hb5,8'hb5,8'hb5,8'hb5,8'hb5,8'hb5,8'hb5,8'hb5,8'h8d,8'hb5,8'hb1,8'hb5,8'hb5,8'hb5,8'h94,8'hb5,8'hb1,8'h94,8'hb4,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hb4,8'hb5,8'hda,8'hb5,8'h6c,8'hb1,8'hb5,8'h91,8'h94,8'hb6,8'hb5,8'hb5,8'hb5,8'hb5,8'hb5,8'hb5,8'hb5,8'hb1,8'hb5,8'hb5,8'hb5,8'hb4,8'h94,8'hb4,8'h94,8'hb4,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hff,8'hb4,8'hb4,8'hda,8'hb5,8'h91,8'hb4,8'hb5,8'hb6,8'hb4,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hb6,8'hb5,8'hb5,8'hb5,8'hb5,8'hb5,8'hb4,8'hb6,8'h94,8'hb5,8'hb6,8'hda,8'hff,8'hff,8'hff},
	{8'hff,8'hff,8'hda,8'h94,8'hb1,8'hb6,8'hb6,8'hb6,8'hb5,8'h8d,8'h91,8'h90,8'hb4,8'hb5,8'hb6,8'hb6,8'hb6,8'hb6,8'hb5,8'hb5,8'hb5,8'hb5,8'h90,8'h94,8'hd6,8'hda,8'hda,8'hda,8'hda,8'hb5,8'hff,8'hff},
	{8'hff,8'hff,8'hda,8'hd6,8'hda,8'hda,8'hda,8'hda,8'hb6,8'hb5,8'h94,8'h94,8'h94,8'hb5,8'hb5,8'hb5,8'hb6,8'hb6,8'hb6,8'hb5,8'hb5,8'h94,8'h90,8'h94,8'hda,8'hb6,8'hd6,8'hda,8'hb6,8'hb1,8'hff,8'hff},
	{8'hff,8'hff,8'hfe,8'hda,8'hb6,8'hb6,8'hda,8'hda,8'hb6,8'hb5,8'h94,8'h94,8'h94,8'hda,8'hda,8'hda,8'h91,8'hb5,8'h91,8'h91,8'hb5,8'hb5,8'h90,8'hb6,8'hd6,8'hb6,8'hda,8'hda,8'hb5,8'h91,8'hff,8'hff},
	{8'hff,8'hff,8'hd6,8'hb6,8'hd6,8'hb6,8'hb5,8'hb6,8'hb6,8'hb5,8'h91,8'h94,8'hb6,8'hb6,8'hb6,8'hb6,8'hda,8'hb1,8'hb6,8'h91,8'hd6,8'hb6,8'hb5,8'hb6,8'hb5,8'hb6,8'hb6,8'hb5,8'hb1,8'h91,8'hff,8'hff},
	{8'hff,8'hff,8'hd6,8'hb6,8'hd6,8'hb6,8'hb5,8'hb6,8'hb6,8'hb5,8'h91,8'h94,8'hb6,8'hb6,8'hb6,8'hb6,8'hda,8'hb1,8'hb6,8'h91,8'hd6,8'hb6,8'hb5,8'hb6,8'hb5,8'hb6,8'hb6,8'hb5,8'hb1,8'h91,8'hff,8'hff},
	{8'hff,8'hff,8'hd6,8'hb6,8'hd6,8'hb6,8'hb5,8'hb6,8'hb6,8'hb5,8'h91,8'h94,8'hb6,8'hb6,8'hb6,8'hb6,8'hda,8'hb1,8'hb6,8'h91,8'hd6,8'hb6,8'hb5,8'hb6,8'hb5,8'hb6,8'hb6,8'hb5,8'hb1,8'hb1,8'hff,8'hff},
	{8'hff,8'hff,8'hd6,8'hb6,8'hd6,8'hb6,8'hb5,8'hb6,8'hb6,8'hb5,8'h91,8'h94,8'hb6,8'hb6,8'hb6,8'hb6,8'hda,8'hb1,8'hb6,8'h91,8'hd6,8'hb6,8'hb5,8'hb6,8'hb5,8'hb6,8'hb6,8'hb5,8'hb1,8'hb1,8'hff,8'hff},
	{8'hff,8'hff,8'hd6,8'hb6,8'hd6,8'hb6,8'hb5,8'hb6,8'hb6,8'hb5,8'h91,8'h94,8'hb6,8'hb6,8'hb6,8'hb6,8'hda,8'hb1,8'hb6,8'h91,8'hd6,8'hb6,8'hb5,8'hb6,8'hb5,8'hb6,8'hb6,8'hb5,8'hb1,8'hb1,8'hff,8'hff}}
	};
 
// assign offsetY_LSB  = offsetY[4:0] ; // get lower 5 bits 
// assign offsetY_MSB  = offsetY[8:5] ; // get higher 4 bits 
// assign offsetX_LSB  = offsetX[4:0] ; 
// assign offsetX_MSB  = offsetX[8:5] ; 


//-------------------------------------------------------	 
logic box_hit_D ;
logic wall_hit_D ;
logic found_two ; // Flag to indicate if a 2 is found


//-------------------------------------------------------

// pipeline (ff) to get the pixel color from the array 
//==----------------------------------------------------------------------------------------------------------------=
always_ff@(posedge clk or negedge resetN)
begin
	if(!resetN) begin
		RGBout <=	8'h00;
		MazeBitMapMask  <=  MazeDefaultBitMapMask[random_matrix_pick] ;  //  copy default tabel 
		found_two <= 1'b0 ;
	end
	
	else begin
	

		 RGBout <= TRANSPARENT_ENCODING ; // default 
		 found_two <= 1'b0;
		 
		 //------------------------------------Check if there are any pigs left-------------------------------------------------
			
		for (int i = 0; i < 16; i++) begin
        for (int j = 0; j < 16; j++) begin
				if (MazeBitMapMask[i][j] == 4'h2)
					found_two <= 1'b1; // Set the flag if '2' is found
        end
      end
		 
//----------------------------------add collision betwenn smiley and pig -- disappear pig  ------------------------------------------		
       if (collision == 1'b1)begin
		 
		   if(MazeBitMapMask[offsetY[8:5]][offsetX[8:5]] == 4'h1)begin
				box_hit_D = 1'b1 ;
				wall_hit_D = 1'b0 ;
            //------------------loop to destroy all boxes/pigs above a box that was hit--------------------------------------
				for(int i=0; i<10; i++)begin
					MazeBitMapMask[offsetY[8:5]-i][offsetX[8:5]] <= MazeBitMapMask[offsetY[8:5]-(i+1)][offsetX[8:5]];
				end
				//---------------------------------------------------------------------------------------------------------------	
			
			end
			
			else if(MazeBitMapMask[offsetY[8:5]][offsetX[8:5]] == 4'h2)begin
				MazeBitMapMask[offsetY[8:5]][offsetX[8:5]] <= 4'h0;
				box_hit_D = 1'b0 ;
				wall_hit_D = 1'b0 ;

			end
			
			else begin
				box_hit_D = 1'b0 ;
				wall_hit_D = 1'b1 ;
			end
				
			
			
		 end
		
//------------------------------------End collision betwenn smiley and Hart------------------------------------------- 		
		
		if (InsideRectangle == 1'b1 )	
			begin 
		   	case (MazeBitMapMask[offsetY[8:5]][offsetX[8:5]])
					 4'h0 : RGBout <= TRANSPARENT_ENCODING ;
					 4'h1 : RGBout <= object_colors[2'h0][offsetY[4:0]][offsetX[4:0]]; 
					 4'h2 : RGBout <= object_colors[2'h1][offsetY[4:0]][offsetX[4:0]] ; 
					 4'h3 : RGBout <= object_colors[2'h2][offsetY[4:0]][offsetX[4:0]] ;
					 default:  RGBout <= TRANSPARENT_ENCODING ; 
				endcase
			end 
		
 
	end 
end

//==----------------------------------------------------------------------------------------------------------------=
// decide if to draw the pixel or not 
assign drawingRequest = (RGBout != TRANSPARENT_ENCODING ) ? 1'b1 : 1'b0 ; // get optional transparent command from the bitmpap   
assign box_hit = box_hit_D ;
assign wall_hit = wall_hit_D ;
assign game_won = (!found_two) ;

endmodule
